project_id = "ihzyuyfawapweamqzzlj"

[functions.ask-circle-ai]
verify_jwt = false

[functions.daily-blessing]
verify_jwt = false

[functions.deploy-dedication]
verify_jwt = false

[functions.auto-import-channels]
verify_jwt = false

[functions.auto-import-trending]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-ghl-contact]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.import-services]
verify_jwt = false

[functions.import-vendors]
verify_jwt = false

[functions.import-youtube-channel]
verify_jwt = false

[functions.invite-vendor]
verify_jwt = false

[functions.promote-top-content]
verify_jwt = false

[functions.send-consultation-notification]
verify_jwt = false

[functions.vectorize-images]
verify_jwt = false

[functions.enhanced-ai-recommendations]
verify_jwt = false

[functions.creator-stripe-onboarding]
verify_jwt = false

[functions.check-creator-onboarding]
verify_jwt = false

[functions.process-creator-payouts]
verify_jwt = false

[functions.get-marketplace-data]
verify_jwt = false

[functions.auto-rerank-services]
verify_jwt = false
schedule = "0 6 * * 1"

[functions.customer-portal]
verify_jwt = false

[functions.pause-subscription]
verify_jwt = false

[functions.apply-discount]
verify_jwt = false

[functions.downgrade-plan]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.resume-subscription]
verify_jwt = false