project_id = "ihzyuyfawapweamqzzlj"

[functions.disc-start]
verify_jwt = true

[functions.disc-status]
verify_jwt = true

[functions.disc-complete]
verify_jwt = true

[functions.disc-webhook]
verify_jwt = false

[functions.questionnaire-save]
verify_jwt = true

[functions.questionnaire-load]
verify_jwt = true

[functions.vendor-demand-digest]
verify_jwt = false

[functions.ask-circle-ai]
verify_jwt = false

[functions.copay-partner-checkout]
verify_jwt = false

[functions.copay-verify-payment]
verify_jwt = false

[functions.daily-blessing]
verify_jwt = false

[functions.deploy-dedication]
verify_jwt = false

[functions.deploy-webhook]
verify_jwt = false

[functions.auto-import-channels]
verify_jwt = false

[functions.auto-import-trending]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-sponsored-checkout]
verify_jwt = false

[functions.create-ghl-contact]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.import-services]
verify_jwt = false

[functions.import-vendors]
verify_jwt = false

[functions.import-youtube-channel]
verify_jwt = false

[functions.invite-vendor]
verify_jwt = false

[functions.promote-top-content]
verify_jwt = false

[functions.send-consultation-notification]
verify_jwt = false

[functions.send-vendor-notification]
verify_jwt = false

[functions.vectorize-images]
verify_jwt = false

[functions.enhanced-ai-recommendations]
verify_jwt = false

[functions.creator-stripe-onboarding]
verify_jwt = false

[functions.check-creator-onboarding]
verify_jwt = false

[functions.process-creator-payouts]
verify_jwt = false

[functions.get-marketplace-data]
verify_jwt = false

[functions.auto-rerank-services]
verify_jwt = false
schedule = "0 6 * * 1"

[functions.customer-portal]
verify_jwt = false

[functions.pause-subscription]
verify_jwt = false

[functions.apply-discount]
verify_jwt = false

[functions.downgrade-plan]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.resume-subscription]
verify_jwt = false

[functions.create-donation]
verify_jwt = false

[functions.track-affiliate-click]
verify_jwt = false

[functions.track-affiliate-conversion]
verify_jwt = false

[functions.generate-affiliate-payouts]
verify_jwt = true

[functions.process-affiliate-stripe-payouts]
verify_jwt = true

[functions.send-vendor-weekly-stats]
verify_jwt = false
schedule = "0 9 * * 1"

[functions.bulk-ai-service-updater]
verify_jwt = false

[functions.get-batch-status]
verify_jwt = false

[functions.auth-signup]
verify_jwt = false

[functions.session-control]
verify_jwt = false

[functions.qbo-connect]
verify_jwt = false

[functions.qbo-callback]
verify_jwt = false

[functions.qbo-webhook]
verify_jwt = false

[functions.qbo-refresh-token]
verify_jwt = false

[functions.qbo-test-invoice]
verify_jwt = false

[functions.simple-openai-chat]
verify_jwt = false

[functions.concierge-respond]
verify_jwt = true

[functions.concierge-ingest]
verify_jwt = true

[functions.concierge-feedback]
verify_jwt = true

[functions.nightly-learning-job]
verify_jwt = false

[functions.send-consultation-alert]
verify_jwt = true

[functions.match-engine]
verify_jwt = false