-- Seed playbooks table with example data
INSERT INTO public.playbooks (
  title, 
  slug, 
  teaser_one_liner,
  duration_minutes,
  price_usd,
  member_price_usd,
  market_city,
  market_state,
  agent_name,
  production_units_l12m,
  production_volume_l12m,
  tier_label,
  team_size,
  niches,
  tools_used,
  highlights,
  outcomes,
  status
) VALUES
(
  'The $50M Luxury Listing Playbook',
  'luxury-listing-playbook',
  'How I dominate high-end real estate with zero paid ads',
  90,
  299.00,
  249.00,
  'Beverly Hills',
  'CA',
  'Marcus Chen',
  42,
  52000000,
  'Top 1%',
  'Solo',
  '["Luxury", "Sellers"]'::jsonb,
  '["Follow Up Boss", "Luxury Presence", "Compass CRM"]'::jsonb,
  '["Built $50M+ pipeline without paid advertising", "Private client events that convert 40%", "Referral system that brings 60% of business"]'::jsonb,
  '["42 closings in 12 months", "$1.2M average sale price", "87% seller-side transactions"]'::jsonb,
  'live'
),
(
  'First-Time Buyer Machine',
  'first-time-buyer-machine',
  'Converting renters to buyers in competitive markets',
  60,
  199.00,
  159.00,
  'Austin',
  'TX',
  'Sarah Mitchell',
  68,
  24500000,
  'Top 5%',
  '2-5',
  '["First-Time Buyers", "Buyers"]'::jsonb,
  '["Zillow Premier", "BombBomb", "kvCORE"]'::jsonb,
  '["Facebook group with 5,000+ renters", "First-time buyer workshop that books 15 appointments/month", "Lender partnership program"]'::jsonb,
  '["68 closings last year", "$360K average price", "94% buyer-side"]'::jsonb,
  'live'
),
(
  'The Circle Prospecting Blueprint',
  'circle-prospecting-blueprint',
  'Door knocking strategy that netted me 31 listings in one year',
  75,
  249.00,
  199.00,
  'Phoenix',
  'AZ',
  'David Rodriguez',
  55,
  31000000,
  'Top 5%',
  'Solo',
  '["Sellers", "Geographic Farm"]'::jsonb,
  '["Mojo Dialer", "REDX", "Canva"]'::jsonb,
  '["Systematic neighborhood targeting", "Script that gets past gatekeepers 70% of the time", "Follow-up cadence that converts prospects in 90 days"]'::jsonb,
  '["55 deals closed", "31 were listings", "$563K average sale price"]'::jsonb,
  'live'
),
(
  'YouTube to $100K+/Month',
  'youtube-content-strategy',
  'Building authority and inbound leads through weekly videos',
  120,
  349.00,
  299.00,
  'Denver',
  'CO',
  'Jessica Park',
  72,
  38000000,
  'Top 1%',
  '6-10',
  '["Content Marketing", "Buyers", "Sellers"]'::jsonb,
  '["Final Cut Pro", "TubeBuddy", "Follow Up Boss"]'::jsonb,
  '["15,000+ YouTube subscribers", "300+ inbound leads per year from content", "Video SEO strategy for local dominance"]'::jsonb,
  '["72 closings", "$528K average price", "85% of leads are inbound"]'::jsonb,
  'live'
),
(
  'The Expired Listing System',
  'expired-listing-system',
  'Converting expired listings with a 47% success rate',
  55,
  279.00,
  229.00,
  'Tampa',
  'FL',
  'Michael Torres',
  49,
  27500000,
  'Top 10%',
  'Solo',
  '["Sellers", "Expired Listings"]'::jsonb,
  '["Vulcan7", "REDX", "Command"]'::jsonb,
  '["Scripts that differentiate from 50 other agents", "Market analysis presentation that wins listings", "Pricing strategy that sells 92% in 30 days"]'::jsonb,
  '["49 deals", "35 from expireds", "$561K average price"]'::jsonb,
  'live'
),
(
  'Investor Deal Flow Factory',
  'investor-deal-flow',
  'Building relationships with investors who buy 3-5 properties per year',
  80,
  249.00,
  199.00,
  'Atlanta',
  'GA',
  'Brandon Lee',
  83,
  29000000,
  'Top 5%',
  '2-5',
  '["Investors", "Buyers"]'::jsonb,
  '["REIPro", "PropStream", "Podio"]'::jsonb,
  '["Deal analyzer spreadsheet investors love", "Monthly investor meetup that fills pipeline", "Off-market sourcing strategy"]'::jsonb,
  '["83 transactions", "22 repeat investors", "$349K average deal"]'::jsonb,
  'live'
),
(
  'The Referral-Only Agent',
  'referral-only-playbook',
  'How I closed 61 deals last year without a single lead purchase',
  65,
  299.00,
  249.00,
  'Nashville',
  'TN',
  'Amanda Foster',
  61,
  32000000,
  'Top 1%',
  'Solo',
  '["Referrals", "Sphere"]'::jsonb,
  '["Real Geeks", "Sendoso", "HubSpot"]'::jsonb,
  '["Client event calendar that generates 40+ referrals/year", "Gift strategy that keeps you top of mind", "Past client reactivation system"]'::jsonb,
  '["61 closings", "100% from referrals and sphere", "$525K average sale"]'::jsonb,
  'live'
),
(
  'New Construction Specialist',
  'new-construction-specialist',
  'Partnering with builders for consistent high-volume deals',
  70,
  229.00,
  179.00,
  'Charlotte',
  'NC',
  'Chris Johnson',
  94,
  41000000,
  'Top 5%',
  '6-10',
  '["New Construction", "Buyers"]'::jsonb,
  '["New Home Star", "BDX", "Salesforce"]'::jsonb,
  '["Builder partnership program", "New construction buyer seminar", "Incentive negotiation tactics"]'::jsonb,
  '["94 closings", "78 new construction", "$436K average"]'::jsonb,
  'live'
),
(
  'The Open House Conversion Pro',
  'open-house-conversion',
  'Turning Sunday open houses into Monday appointments',
  50,
  199.00,
  159.00,
  'San Diego',
  'CA',
  'Rachel Kim',
  58,
  28500000,
  'Top 10%',
  '2-5',
  '["Buyers", "Open Houses"]'::jsonb,
  '["Spacio", "Follow Up Boss", "BombBomb"]'::jsonb,
  '["Pre-open house marketing system", "On-site conversion tactics", "48-hour follow-up sequence"]'::jsonb,
  '["58 deals", "32 from open house leads", "$491K average"]'::jsonb,
  'live'
),
(
  'Instagram DM to Closing',
  'instagram-dms-to-deals',
  'Social media strategy that generated 45 deals in 12 months',
  85,
  269.00,
  219.00,
  'Miami',
  'FL',
  'Alex Rivera',
  45,
  25000000,
  'Top 10%',
  'Solo',
  '["Social Media", "Buyers", "Sellers"]'::jsonb,
  '["Later", "Canva", "ManyChat"]'::jsonb,
  '["Content calendar that attracts ideal clients", "DM conversation framework", "Story strategy for daily engagement"]'::jsonb,
  '["45 closings", "38 from Instagram", "$556K average price"]'::jsonb,
  'live'
);